### ISSUE TITLE
Reasoner Break Up

### ISSUE THREAD

**Issue by jsimonclark** [emmo-repo/domain-characterisation-methodology#10]
When reasoning with HermiT 1.4.3.456, it runs for a very long time (over an hour) and eventually breaks up. 

I tried the following actions, but none yielded a meaningful improvement:
- remove qualified cardinality restrictions
- remove hasProperty relations
- import all of emmo instead of just certain modules

**Comment by jsimonclark** [comment]
UPDATE: I removed all the restrictions in CHAMEO and it reasoned successfully (although it still took a long time). So, one of the restrictions is causing a hang-up, but I'm not sure which one it is.

Are you using any special settings in the reasoner?

**Comment by pierluigidelnostro** [comment]
No special settings in the reasoner. We are checking the restrictions to see which cause the issue.

**Comment by jsimonclark** [comment]
Thank you. Any update so far? It's blocking us from being able to fully reason domain-electrochemistry. At the moment I'm getting around it by removing the chameo import for the pre-inferred version.

**Comment by pierluigidelnostro** [comment]
The issue should be resolved. Now it should take 7 to 10 minutes depending on the computer.

**Comment by jesper-friis** [comment]
Great to hear. What have you changed?

**Comment by pierluigidelnostro** [comment]
I have removed the individuals
